url: https://sanduni-p.github.io/IntroR-tidyverse/
project:
  type: website

website:
  title: "Introduction to R: Exploring the tidyverse"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Workshop Materials
        menu:
        - text: "Basics of R Programming Language"
          href: vignettes/1_Introduction.html
        - text: "Reading and Tidying Data"
          href: vignettes/2_Reading_tidying_data.html
        - text: "Transforming and Joining Data"
          href: vignettes/3_Data_Manipulation.html  
        - text: "Visualizing Data"
          href: vignettes/4_Visualization.html
        - text: "Exploring the Metabric Dataset"
          href: vignettes/5_Exploring_Metabric.html    
format:
  html:
    theme: 
      - cerulean
      - utils/css/custom.scss
    toc: true
    toc-expand: 1
    toc-title: Contents
    embed-resources: true
    css: utils/css/custom.css
    smooth-scroll: true
    df-print: kable
execute: 
  freeze: auto

